language: python

services:
  - docker

before_install:
    - docker build -q -t dreem -f docker/Dockerfile .

install:
  - pip install -r requirements.txt
  - pip install future
  - pip install  .


script:
  - pytest
  - python dreem/run_docker.py -fa test/resources/case_1/test.fasta -fq1 test/resources/case_1/test_mate1.fastq -fq2 test/resources/case_1/test_mate2.fastq --dot_bracket test/resources/case_1/test.csv
  # make sure single reads work too
  - python dreem/run_docker.py -fa test/resources/case_1/test.fasta -fq1 test/resources/case_1/test_mate1.fastq
  # Check if this was ever really passing
  - if [[ -f output/BitVector_Files/mttr-6-alt-h3_bitvectors.txt ]]; then exit 1; fi

